# Generated by Django 5.2 on 2025-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(help_text='Kenglik (Longitude)')),
                ('lat', models.FloatField(help_text='Uzunlik (Latitude)')),
                ('address_uz', models.CharField(help_text="Manzil (O'zbekcha)", max_length=255)),
                ('address_ru', models.CharField(help_text='Manzil (Ruscha)', max_length=255)),
                ('address_en', models.CharField(help_text='Manzil (Inglizcha)', max_length=255)),
                ('address_de', models.CharField(help_text='Manzil (Nemischacha)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lokatsiya',
                'ordering': ['created_at'],
            },
        ),
    ]
