# Generated by Django 5.2 on 2025-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='admissionstep',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Qabul bosqichlari'},
        ),
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['-is_read', '-created_at'], 'verbose_name_plural': "Qabul so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['-created_at'], 'verbose_name_plural': "Bizning ta'limni foydalari"},
        ),
        migrations.AlterModelOptions(
            name='courselevel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Kurs darajalari'},
        ),
        migrations.AlterModelOptions(
            name='curriculumsubject',
            options={'ordering': ['-created_at'], 'verbose_name_plural': "O'quv dasturi fanlari"},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Galereya'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bizning sayohat'},
        ),
        migrations.AlterModelOptions(
            name='teachingmethodology',
            options={'ordering': ['title_uz'], 'verbose_name_plural': "O'qitish metodologiyalari"},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bizning qiymatimiz'},
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook havola'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='insta_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram havola'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedIn_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIN havola'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X havola'),
        ),
    ]
