# Generated by Django 5.2 on 2025-04-30 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_options_alter_admissionstep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name_uz'], 'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name_de',
            new_name='full_name_de',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name_en',
            new_name='full_name_en',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name_ru',
            new_name='full_name_ru',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name_uz',
            new_name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_de',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_uz',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='certifications_de',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='certifications_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='certifications_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='certifications_uz',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='from_country',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name_de',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name_uz',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(default='Default Feature, change it!'),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook havola'),
        ),
        migrations.AlterField(
            model_name='info',
            name='insta_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram havola'),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedIn_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIN havola'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Noto'g'ri telefon raqami")]),
        ),
        migrations.AlterField(
            model_name='info',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram havola'),
        ),
        migrations.AlterField(
            model_name='info',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X havola'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_level_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_level_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_level_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_level_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
