# Generated by Django 5.2 on 2025-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='features',
            new_name='features_de',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features_en',
            field=models.TextField(default='Default Feature, change it!'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features_ru',
            field=models.TextField(default='Default Feature, change it!'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features_uz',
            field=models.TextField(default='Default Feature, change it!'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram havola'),
        ),
    ]
