# Generated by Django 5.2 on 2025-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_features_subscription_features_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.CharField(max_length=20)),
                ('discount_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Chegirma tavsifi',
                'ordering': ['discount_text', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Tavsif (de)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (en)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (ru)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (uz)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features_de',
            field=models.TextField(default='Default Feature, change it!', verbose_name='Xususiyatlari (de)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features_en',
            field=models.TextField(default='Default Feature, change it!', verbose_name='Xususiyatlari (en)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features_ru',
            field=models.TextField(default='Default Feature, change it!', verbose_name='Xususiyatlari (ru)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features_uz',
            field=models.TextField(default='Default Feature, change it!', verbose_name='Xususiyatlari (uz)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obuna turi (de)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obuna turi (en)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obuna turi (ru)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obuna turi (uz)'),
        ),
    ]
