# Generated by Django 5.2 on 2025-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_admissiondiscount_alter_subscription_description_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiondiscount',
            options={'ordering': ['discount_text_uz', '-created_at'], 'verbose_name_plural': 'Chegirma tavsifi'},
        ),
        migrations.RemoveField(
            model_name='admissiondiscount',
            name='discount_text',
        ),
        migrations.AddField(
            model_name='admissiondiscount',
            name='discount_text_de',
            field=models.TextField(default='Defaoult discount text, change it in Admin panel!', verbose_name='Chegirma tavsifi (DE)'),
        ),
        migrations.AddField(
            model_name='admissiondiscount',
            name='discount_text_en',
            field=models.TextField(default='Defaoult discount text, change it in Admin panel!', verbose_name='Chegirma tavsifi (EN)'),
        ),
        migrations.AddField(
            model_name='admissiondiscount',
            name='discount_text_ru',
            field=models.TextField(default='Defaoult discount text, change it in Admin panel!', verbose_name='Chegirma tavsifi (RU)'),
        ),
        migrations.AddField(
            model_name='admissiondiscount',
            name='discount_text_uz',
            field=models.TextField(default='Defaoult discount text, change it in Admin panel!', verbose_name='Chegirma tavsifi (UZ)'),
        ),
    ]
